services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    expose:
      - "${BACKEND_PORT}"
    environment:
      FLASK_ENV: development
      BACKEND_PORT: "${BACKEND_PORT}"  # Pass the port into the backend environment
      FRONTEND_PORT: "${FRONTEND_PORT}"      
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    expose:
      - "${FRONTEND_PORT}"
    environment:
      FLASK_ENV: development
      BACKEND_URL: "${BACKEND_URL}"  # Pass the backend URL to the frontend
      FRONTEND_PORT: "${FRONTEND_PORT}"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
