version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    expose:
      - "5001"
    environment:
      FLASK_ENV: development
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    expose:
      - "5000"
    environment:
      FLASK_ENV: development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
