name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Python Tests Job for Backend
  backend_tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment for unit tests
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      # Install backend dependencies for unit tests
      - name: Install backend dependencies
        working-directory: flask-flask-square/backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run backend unit tests
      - name: Run backend unit tests
        working-directory: flask-flask-square/backend
        run: |
          pytest tests/

  # Docker Build and Integration Test Job
  container_integration_tests:
    runs-on: ubuntu-latest
    needs: backend_tests  # This job runs only if the unit tests pass

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install pytest in the GitHub Actions environment
      - name: Install pytest for integration tests
        run: |
          pip install pytest

      # Build Backend Docker Image
      - name: Build backend container
        working-directory: flask-flask-square/backend
        run: |
          docker build -t backend:latest .

      # Run Backend Container
      - name: Run backend container
        run: |
          docker run -d --name backend -p 3001:3001 backend:latest
          sleep 10  # Wait for the backend to start up

      # Run Container Integration Tests
      - name: Run backend container integration tests
        working-directory: flask-flask-square/backend
        run: |
          pytest tests_container/

      # Stop and remove the backend container
      - name: Stop and remove container
        run: |
          docker stop backend
          docker rm backend
